[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features=["full"] }
axum = { version = "0.8.4", features = ["ws"] }
futures-util = "0.3.31"
tower-http = {version = "0.6.4", features=["cors"]}